apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 1337
          env:
            - name: NGINX_PORT
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: nginx_port
            - name: NGINX_GZIP
              valueFrom:
                configMapKeyRef:
                  name: nginx-configmap
                  key: nginx_gzip
